### ISSUE TITLE
第三章测试 /etc/named.conf文件不存在

### ISSUE THREAD

**Issue by Luxing-PP** [22dm/linux_faq#10]
**个人信息**
学号：191250009
机器：172.29.4.109
root/vnc 密码： 20200719

**问题描述**
在完成 “使用命令将“cat /etc/named.conf”设置为别名name，然后再取消别名。 ” 时
显示不存在该文件

**我已经做了什么**
简单的检索和查看/etc目录

**我希望看到什么**
就希望能够知道（查看）该文件的实际位置，或者得到不存在情况下完成作业的替代方案

**屏幕截图**
![屏幕截图(1812)](https://user-images.githubusercontent.com/56151286/87870343-8d10dc00-c9d9-11ea-99c9-8274ab0899d0.png)

**Comment by 22dm** [comment]
只需要对此命令设置别名即可，不需要文件存在。也可自行创建此文件，但这与作业内容无关。

**Comment by zengsheng163** [comment]
使用#yum install bind安装软件就会有named.conf，或者自行创建此文件后完成实验。
