### ISSUE TITLE
VNC 连接超时

### ISSUE THREAD

**Issue by lollipop190** [22dm/linux_faq#12]
**个人信息**
- 学号：191250190
- 机器：172.29.4.138
- root 密码：20010328
- vnc 密码：20010328

**描述你的问题**
我在本地通过 VNC 连接主机时，出现了连接超时的问题

**你已经做了什么**
- 在昨天已经在云端配置好了机器，并且刚刚也可以正常使用。
- 而后进入系统后我试图关闭早上课上开启的firefox，发现似乎出现了死机现象并自动退出，vnc连接也断开
- 而后我就出现了连接超时的问题
- 随后我在云主机中尝试了重启和强制重启，还是无法解决此问题。

**你希望看到什么**
- 本地通过 VNC 连接到云主机

**屏幕截图**
![$8GZ 3$@J7YH@S9R@%JF3L1](https://user-images.githubusercontent.com/58462846/87873081-ef290b80-c9f0-11ea-91bc-e9ddc7b5e0f5.png)
![EEX}{HKL6VNB6Y($O907YHK](https://user-images.githubusercontent.com/58462846/87873084-f18b6580-c9f0-11ea-96ee-1e28280f59d6.png)

**附加信息**
- 我可以通过 ssh 连接到云主机
- vnc的初始界面中，虚拟机的画面停留在了firefox的页面中我已上传了截图。

**Comment by 22dm** [comment]
请提供以下信息：能否使用云平台中的网页版 VNC 进行连接？

**Comment by lollipop190** [comment]
谢谢助教，通过云平台中的vnc进行连接后可以正常使用了。

**Comment by 22dm** [comment]
与 #1 重复
