### ISSUE TITLE
在终端中操作显示权限不够

### ISSUE THREAD

**Issue by Raquelnjq** [22dm/linux_faq#16]
**个人信息**
学号：191250107

**问题描述**
怎样能对系统做各种操作？
部分操作总是显示：权限不够
![image](https://user-images.githubusercontent.com/68494887/87974269-64353780-cafc-11ea-9a1f-6d52cdd1ffca.png)

**Comment by D-W-X** [comment]
你登陆的是njq这个用户，而/root目录只有root用户才可以写入

**Comment by Raquelnjq** [comment]
那怎么登陆root用户呢？只有这一个用户呀.....

**Comment by D-W-X** [comment]
登录用户
- ssh：输入 ssh root@ip
- 命令行客户端：在 `XXX Login:` 输入root
- 图形界面：选择密码框下的 `未列出` ，输入root

身份切换：
- 输入`su`，输入root密码
- 如果用户具有管理员权限，输入`sudo su`，输入用户密码

直接执行：
- 如果用户有管理员权限，输入`sudo [command]`，输入用户密码
