### ISSUE TITLE
登录账户出现问题

### ISSUE THREAD

**Issue by RongXing2012** [22dm/linux_faq#18]
**个人信息**
- 学号：181250120

**描述你的问题**
登录root账户的时候出现问题：gkbd-keyboard-display killed by SIGSEGV，请问该如何解决？
![5](https://user-images.githubusercontent.com/56295972/88037802-f62e5600-cb77-11ea-9ff1-e89b9f93aa57.png)

**Comment by D-W-X** [comment]
提供root账号密码

**Comment by RongXing2012** [comment]
> 提供root账号密码

账户：root
密码：123321qaz

**Comment by D-W-X** [comment]
目前无法定位到具体问题，可能由于GUI相关出现问题，不是由于su命令本身引起的。

如需避免问题，请考虑使用ssh登录设备。

此问题可以暂时忽略，不影响系统的正常使用。

**Comment by RongXing2012** [comment]
> 提供root账号密码

账户：root
密码：123321qaz

**Comment by RongXing2012** [comment]
不知道怎么回事，恢复正常了。。。
