### ISSUE TITLE
n的具体含义不清

### ISSUE THREAD

**Issue by jiaxinr** [22dm/linux_faq#19]
**个人信息**
学号：191250170

**问题描述**
课后作业第六章第5题：使用for语句创建一个Shell程序，其功能为1+2+3+4+5······+n。
上述问题中的n具体含义不清，是否代表从命令行上获取？

**Comment by D-W-X** [comment]
可以有以下处理
- 在执行时等待用户输入
- 以参数的形式传入
- 读取shell中环境变量相关值，检查如果环境变量相关值不存在则设置一个默认值
