### ISSUE TITLE
删除重建云主机时配额超限

### ISSUE THREAD

**Issue by Sher9876** [22dm/linux_faq#2]
**个人信息**
- 学号：191250162
- 机器：172.29.4.67

**描述你的问题**
我删除了云主机想重建的时候显示配额超限

**你已经做了什么**

**你希望看到什么**
- 新建一个云主机

**屏幕截图**

![4K%U9`M`D A 5CF66)IQ ZV](https://user-images.githubusercontent.com/68471119/87854563-6012e980-c945-11ea-9b08-c966ef4ea4b2.png)

**附加信息**
- 我之前安装好了linux系统，登录时密码错误所以删除了云主机

**Comment by 22dm** [comment]
请确认云硬盘是否已经删除，点击左侧 “储存” - “云硬盘”，在其中删除云硬盘

**Comment by Sher9876** [comment]
> 请确认云硬盘是否已经删除，单击上方的“存储”-“云硬盘”，如果其中存在云硬盘，在将其删除

存在云硬盘，显示在使用中，但是无法删除

**Comment by Sher9876** [comment]
我彻底删除了云主机，然后就可以了
