### ISSUE TITLE
ssh无法连接，屏幕共享中显示没有网络，无法打开屏幕共享开关

### ISSUE THREAD

**Issue by NIL-zhuang** [22dm/linux_faq#22]
**个人信息**
- 学号：181830266
- 机器：172.29.4.69
- root 密码：centos
- vnc 密码：centos

**描述你的问题**
通过windows terminal 的ssh命令port 22连接主机时出现time out

**你已经做了什么**
- 我检查了安全组的设置，符合《课程指南》中的描述
- 已安装好centos系统

**你希望看到什么**
- 本地通过 ssh和vnc 连接到云主机

**屏幕截图**
![image](https://user-images.githubusercontent.com/46214362/88158004-10cb0280-cc3e-11ea-9be1-bf9c4efb5d5d.png)

**附加信息**
- 无法将系统的屏幕共享设置成activce

**Comment by D-W-X** [comment]
你在安装系统时没有设置网络，打开系统后也没有配置网络，因此无法打开屏幕共享，请后续步骤按照指南一步一步操作，不要跳步。
已帮你打开，现在恢复正常。
