### ISSUE TITLE
rpm：没有那个文件或目录

### ISSUE THREAD

**Issue by yst001** [22dm/linux_faq#23]
**个人信息**
- 学号：181250173
- 机器：172.29.4.208
- root 密码：yst206614
- vnc 密码：206614

**描述你的问题**
我在本地RPM安装依赖包报没有那个文件或目录的错误
![image](https://user-images.githubusercontent.com/44132305/88259183-61049c00-ccf4-11ea-9dd1-1d8286cee1f2.png)

**你已经做了什么**
- 尝试在网络上搜解决方案，可是收到需要rpm挂载的Packages目录下安装，可是我的本地好像没有Packages目录

**你希望看到什么**
- rpm依赖可以成功安装

**屏幕截图**

**附加信息**
- rpm的其他命令正常，网络也已经在Firefox里面连接了

**Comment by 22dm** [comment]
你需要先手动下载这个 rpm 包到当前目录

**Comment by pppppkun** [comment]
在网上下载这个包，然后用rpm安装
ssh里面可以使用curl -O <url>来下载
