### ISSUE TITLE
重启后，通过云平台VNC连接主机不再出现图形界面

### ISSUE THREAD

**Issue by cqsb** [22dm/linux_faq#24]
**个人信息**
- 学号：171840773
- 机器：172.29.4.126
- root 密码：123456
- vnc 密码：123456

**描述你的问题**
我在云平台重启主机后通过 VNC 连接主机时，不再看到图形界面

**你已经做了什么**
- 我仔细阅读过《课程指南》中相关章节，尝试过输入 firewalld 的那行命令，无效
- 我检查了安全组的设置，符合《课程指南》中的描述

**你希望看到什么**
- 云端通过 VNC 连接到云主机时可以看到图形界面

<img width="874" alt="image" src="https://user-images.githubusercontent.com/55623950/88265080-69ae9f80-ccff-11ea-9dcd-ba26060c8d5e.png">

**Comment by cqsb** [comment]
如题

**Comment by 22dm** [comment]
请按按照要求模版

**Comment by Raquelnjq** [comment]
有相同问题，是在将网卡名称eno16777736更改为eth0，终端reboot之后出现这个情况
![image](https://user-images.githubusercontent.com/68494887/88456612-7d016c80-ceb1-11ea-8512-544c7eef0468.png)

**Comment by 22dm** [comment]
1. 在提此类问题时，请注明自己的机器登录信息（原问题中的登录信息为模版内容）
2. 请提供之前进行的操作内容
3. 请先自己尝试重装，99% 都是你自己改错了配置
