### ISSUE TITLE
rpm 安装 bind-chroot：用户 / 群组 named 不存在

### ISSUE THREAD

**Issue by Leonezhurui** [22dm/linux_faq#25]
个人信息
学号：181250212
机器：172.29.4.95
root 密码：Zr200012
vnc 密码：Zr200012

描述你的问题
rpm安装bind-chroot为什么出现很多的组群和用户named不存在

image
<img width="722" alt="rpm-ivh" src="https://user-images.githubusercontent.com/58123081/88266116-3a992d80-cd01-11ea-8143-fd974307a4f7.png">

你已经做了什么
尝试在网络上搜解决方案，重试了几次。

你希望看到什么
rpm依赖可以成功安装

屏幕截图

附加信息

rpm的其他命令正常，网络也已经在Firefox里面连接了

**Comment by 22dm** [comment]
你缺少了依赖，请不要使用 `--nodeps` 进行安装

**Comment by Leonezhurui** [comment]
确实是缺少依赖，但是为什么同样的操作有的同学不存在这个问题呢？

**Comment by 22dm** [comment]
他们可能之前通过其他途径安装过了相关依赖，这里缺的应该是 `bind` 包，比较常见
