### ISSUE TITLE
rpm命令执行超时

### ISSUE THREAD

**Issue by whateverend** [22dm/linux_faq#27]
**个人信息**
- 学号：181250067
- 机器：192.168.1.108
- root 密码：123456
- vnc 密码：123456

**描述你的问题**
我在本地运行rpm -ivh ...命令，输入回车后什么都不显示

**你已经做了什么**
- 在/root/install文件夹下安装好bind-chroot-9.11.4-16.P2.el7.x86_64.rpm后运行rpm安装命令

**你希望看到什么**
- 出现安装时“依赖不足”的提示

**屏幕截图**
[https://seec-invictus.oss-cn-beijing.aliyuncs.com/graph/5.4.png](url)

**附加信息**
- 我可以通过 ssh 连接到本地虚拟机

**Comment by 22dm** [comment]
有可能是之前的 rpm 进程没有结束，之后的 rpm 在等待锁，请按照以下步骤尝试：
- 重启虚拟机
- 执行 `rm -f /var/lib/rpm/.rpm.lock`
- 执行 `rpm --rebuilddb`
- 执行 `rpm -ivh 要安装的软件包`

**Comment by whateverend** [comment]
谢谢老师，已解决
