### ISSUE TITLE
rpm安装镜像文件中的软件包时提示更新的已经安装

### ISSUE THREAD

**Issue by icimence** [22dm/linux_faq#28]
**个人信息**
学号：181250022

**问题描述**
在安装bind-license的时候提示更新的版本已经安装，但是使用卸载命令时提示没有安装软件包。
![image](https://user-images.githubusercontent.com/34977758/88283169-8063ef00-cd1d-11ea-9ba1-d975fbd9b82c.png)

**Comment by 22dm** [comment]
删除软件包时不需要加 .rpm 后缀，注意删除的过程也要满足依赖关系，可能会被要求先删除其他软件包

**Comment by icimence** [comment]
用学校的云主机搞定了，谢谢助教
