### ISSUE TITLE
rpm 安装bind-chroot时发生错误

### ISSUE THREAD

**Issue by goldenfingergreenhandblackheart** [22dm/linux_faq#29]
**个人信息**
学号：181250074

**问题描述**
rpm执行安装指令时一直报错
![5JJB}R80D7HMO{SQ0BI(JQ0](https://user-images.githubusercontent.com/48791973/88286574-8957bf00-cd23-11ea-900d-33537ecf9673.png)

**Comment by 22dm** [comment]
你的下载地址有误，请重新核对

**Comment by goldenfingergreenhandblackheart** [comment]
> 你的下载地址有误，请重新核对

好的，感谢助教

**Comment by goldenfingergreenhandblackheart** [comment]
> 你的下载地址有误，请重新核对

我和同学下载的地址都相同，但好像只有我的是错的

**Comment by D-W-X** [comment]
请尝试将http修改为https

**Comment by goldenfingergreenhandblackheart** [comment]
> 请尝试将http修改为https，并确保已经登录P认证

额，请问已经登陆P认证是啥啊

**Comment by D-W-X** [comment]
p.nju.edu.cn

**Comment by 22dm** [comment]
或者尝试南大镜像：https://mirrors.nju.edu.cn/centos/7/os/x86_64/Packages/bind-chroot-9.11.4-16.P2.el7.x86_64.rpm

**Comment by goldenfingergreenhandblackheart** [comment]
> p.nju.edu.cn

成功了，现在不报这个错误了。非常感谢！但是还想请问这是什么原因呢？

**Comment by goldenfingergreenhandblackheart** [comment]
> 或者尝试南大镜像：https://mirrors.nju.edu.cn/centos/7/os/x86_64/Packages/bind-chroot-9.11.4-16.P2.el7.x86_64.rpm

好的

**Comment by D-W-X** [comment]
实际下载的文件是一个404的html文件而不是你想要的文件，因为你访问的中科大域名需要出校，使用虚拟机等同于你在学校连接校园网，不登录是无法正常访问校外ipv4的。
因此需要登录P认证。

**Comment by goldenfingergreenhandblackheart** [comment]
> 实际下载的文件是一个404的html文件而不是你想要的文件，因为你访问的中科大域名需要出校，使用虚拟机等同于你在学校连接校园网，不登录是无法正常访问校外ipv4的。
> 因此需要登录P认证。

了解了，非常感谢您！
