### ISSUE TITLE
在grub菜单按e后没有出现登录的相关内容

### ISSUE THREAD

**Issue by CSYZQ** [22dm/linux_faq#33]
**个人信息**
学号：191250188

**问题描述**
按照ppt来，进入grub菜单按e出现这个情况
![1](https://user-images.githubusercontent.com/55938455/88387479-16168180-cde5-11ea-969f-9010f35a94be.png)

**Comment by 22dm** [comment]
请尝试使用下方的 input 进行输入

**Comment by CSYZQ** [comment]
是设置GRUB2 PBKDF2加密口令这个实验

**Comment by 22dm** [comment]
请按规范填写模版，重新提交 “Linux 系统问题” 类 issue，包含：你已经做了什么，你期望看到什么

**Comment by CSYZQ** [comment]
![1](https://user-images.githubusercontent.com/55938455/88389568-4d872d00-cde9-11ea-9af1-960701d6e89d.png)
![2](https://user-images.githubusercontent.com/55938455/88389663-7c9d9e80-cde9-11ea-9705-da5f467bc68d.png)
然后重启，不显示enter username那个
