### ISSUE TITLE
在设置GRUB2 PBKDF2加密口令实验中，进入grub菜单按e后未出现enter username 相关内容

### ISSUE THREAD

**Issue by CSYZQ** [22dm/linux_faq#34]
**个人信息**
- 学号：191250188
- 机器：172.29.4.85
- root 密码：123456

**描述你的问题**
我在设置GRUB2 PBKDF2加密口令实验中，进入grub菜单按e后未出现enter username 相关内容
**你已经做了什么**

![2](https://user-images.githubusercontent.com/55938455/88389948-16fde200-cdea-11ea-8154-bb12dc2716f0.png)
![1](https://user-images.githubusercontent.com/55938455/88389964-1b29ff80-cdea-11ea-859b-a106daeaae59.png)

**你希望看到什么**
- 成功进入enter username 界面

**Comment by CSYZQ** [comment]
![1](https://user-images.githubusercontent.com/55938455/88390067-43b1f980-cdea-11ea-95c7-ee1dfe2a4322.png)
![2](https://user-images.githubusercontent.com/55938455/88390074-46acea00-cdea-11ea-85f6-1728e55bdf0f.png)

**Comment by CSYZQ** [comment]
为什么截图放不了

**Comment by 22dm** [comment]
请提供你的 /etc/grub.d/00_header 文件内容

**Comment by CSYZQ** [comment]
怎么把内容全部复制出来啊，我看网上的ggyG，我试了好像没有用

**Comment by 22dm** [comment]
截图就行了啊

**Comment by CSYZQ** [comment]
全部截图的话有点多，如果是就我自己输入的那些的话我记得我上面有截图

**Comment by 22dm** [comment]
并没有

**Comment by CSYZQ** [comment]
![88389964-1b29ff80-cdea-11ea-859b-a106daeaae59](https://user-images.githubusercontent.com/55938455/88391509-e9fefe80-cdec-11ea-9912-816391b91fc7.png)
是这个吗

**Comment by 22dm** [comment]
不是，这是个 shell 命令

**Comment by CSYZQ** [comment]
额，我就是把这个写道了header里面

**Comment by CSYZQ** [comment]
![3](https://user-images.githubusercontent.com/55938455/88391741-58dc5780-cded-11ea-8e6b-4a09ba256ff5.png)

**Comment by 22dm** [comment]
请严格按照 ppt 中的描述以及老师上课演示来操作，不要随便找其他教程

**Comment by CSYZQ** [comment]
ppt上没讲怎么添加超级用户

**Comment by CSYZQ** [comment]
找到问题了，当时输入的是中文输入法的引号
