### ISSUE TITLE
无法进入grub2菜单

### ISSUE THREAD

**Issue by sangfroid020** [22dm/linux_faq#35]
**个人信息**
学号：191250084
**问题描述**

已经做了什么？
按照ppt的描述操作，在这里按e后界面提示输入用户和密码，而无法直接进入grub界面
![image](https://user-images.githubusercontent.com/57228638/88390203-7fe55a00-cdea-11ea-84e9-6f997f268398.png)
![image](https://user-images.githubusercontent.com/57228638/88390222-870c6800-cdea-11ea-831a-49de65672222.png)

**Comment by 22dm** [comment]
你按照哪一节进行的操作？

**Comment by sangfroid020** [comment]
> 你按照哪一节进行的操作？

11.6节GRUB2配置案例—>破解用户密码

**Comment by 22dm** [comment]
你是否设置过  PBKDF2 加密口令？

**Comment by sangfroid020** [comment]
> 你是否设置过 PBKDF2 加密口令？

有设置过

**Comment by 22dm** [comment]
那就直接输入密码啊

**Comment by sangfroid020** [comment]
哦前面忘记了还有设置过加密，打扰了
