### ISSUE TITLE
开机按e后，无法进入Grub菜单

### ISSUE THREAD

**Issue by S1XCamus** [22dm/linux_faq#37]
**个人信息**
- 学号：181250122
- 机器：172.29.4.96
- root 密码：aptx4869
- vnc 密码：aptx4869

**描述你的问题**
使用云平台完成破解密码的作业时，按e直接进入了输username的界面

**你已经做了什么**
- 尝试了类似问题下的解决方案：systemctl reboot，没有效果，仍然是按e直接进入输username的界面

**你希望看到什么**
- 按e进入grub菜单

**屏幕截图**

（图片一直显示上传失败）

**附加信息**

**Comment by 22dm** [comment]
请看 #35
