### ISSUE TITLE
lvm无法创建物理卷

### ISSUE THREAD

**Issue by tscRubbish** [22dm/linux_faq#38]
**个人信息**
学号：191250129

**问题描述**
lvm指定一个新创建分区创建物理卷时出现
![image](https://user-images.githubusercontent.com/61186329/88453507-14f35c00-ce9a-11ea-8147-03d0cfb12c4e.png)

**Comment by 22dm** [comment]
你的设备上不存在 /dev/vdb2，请检查你输入的设备名

**Comment by tscRubbish** [comment]
![image](https://user-images.githubusercontent.com/61186329/88454769-525ce700-cea4-11ea-8893-0c445ad9418c.png)
![image](https://user-images.githubusercontent.com/61186329/88454775-60ab0300-cea4-11ea-8256-8a247da28b9b.png)

**Comment by tscRubbish** [comment]
在fdisk的p命令中有/dev/vdb2啊

**Comment by 22dm** [comment]
请给出你的 /etc/lvm/lvm.conf 文件内容

**Comment by tscRubbish** [comment]
> 你的设备上不存在 /dev/vdb2，请检查你输入的设备名

在fdisk的p命令中有/dev/vdb2啊

**Comment by tscRubbish** [comment]
[lvm.zip](https://github.com/22dm/linux_faq/files/4975415/lvm.zip)

**Comment by 22dm** [comment]
请执行以下命令后再次尝试：
1. `umount /dev/vdb2`
2. `partprobe`

如果仍然报错，请给出上述命令的输出与机器的登录信息

**Comment by tscRubbish** [comment]
![image](https://user-images.githubusercontent.com/61186329/88455237-496d1500-cea6-11ea-9071-a398a118f1b6.png)

**Comment by 22dm** [comment]
请重启系统后操作

**Comment by tscRubbish** [comment]
![image](https://user-images.githubusercontent.com/61186329/88455327-0a8b8f00-cea7-11ea-8a6e-e22c4f80e0f9.png)

**Comment by tscRubbish** [comment]
打不开了

**Comment by tscRubbish** [comment]
![image](https://user-images.githubusercontent.com/61186329/88455354-37d83d00-cea7-11ea-89e0-fd9dad3647c2.png)

**Comment by 22dm** [comment]
重装吧，估计你之前搞坏了什么
