### ISSUE TITLE
VNC 连接失败

### ISSUE THREAD

**Issue by whateverend** [22dm/linux_faq#40]
**个人信息**
- 学号：181250067
- 机器：192.168.1.108
- root 密码：123456
- vnc 密码：123456

**描述你的问题**
我在本地通过 VNC 连接主机时，出现了连接失败的问题

**你已经做了什么**
- 关闭防火墙
- 开启了屏幕共享
- 开启了VNC服务

**你希望看到什么**
- 本地通过 VNC 连接到本地虚拟机

**屏幕截图**

> https://seec-invictus.oss-cn-beijing.aliyuncs.com/graph/10.png

**附加信息**
- 我可以通过 ssh 连接到本地虚拟机

**Comment by 22dm** [comment]
请按照课程指南中的步骤操作
