### ISSUE TITLE
在虚拟机中完成作业

### ISSUE THREAD

**Issue by darcy823** [22dm/linux_faq#42]
**个人信息**
-学号: 191250022
. 机器: 本地虚拟机
![image](https://user-images.githubusercontent.com/54134416/88457776-d40c3f00-cebb-11ea-869e-a16d442fffd0.png)

- root密码: 720806

**描述你的问题**
ssh连接超时
ps：vbox屏幕问题导致看不见防火墙下端的按钮，未找到解决办法（全屏、改变显示率都不行）

“"你已经做了什么**
尝试不同网卡的ip地址，powershell和putty平台；
检查ssh是否安装；
检查防火墙是否允许ssh
尝试《课程指南》中的有关描述

**你希望看到什么**
可以通过ssh连接到虚拟机

“屏幕截图*
![image](https://user-images.githubusercontent.com/54134416/88457807-133a9000-cebc-11ea-8486-304fc542779a.png)

**Comment by 22dm** [comment]
请按照 #30 的操作关闭 selinux，或者自行搜索 selinux 相关教程

**Comment by 22dm** [comment]
本地网络环境较为复杂，可以自行在网络搜索相关虚拟机教程进行处理，或尝试在云平台中操作
