### ISSUE TITLE
安装tigervnc-server软件包后未找到命令vncserver

### ISSUE THREAD

**Issue by Raquelnjq** [22dm/linux_faq#47]
**个人信息**
学号：191250107

**问题描述**
配置VNC服务器过程中，安装tigervnc-server软件包后未找到命令vncserver
问题如下：
![image](https://user-images.githubusercontent.com/68494887/88464054-31b78000-ceea-11ea-9d26-8a82aedf9383.png)
尝试过解决如下（失败）：
![image](https://user-images.githubusercontent.com/68494887/88464071-4b58c780-ceea-11ea-8978-ee212c9c54b0.png)

**Comment by 22dm** [comment]
yum 安装失败了啊，检查一下你的 repo 文件
