### ISSUE TITLE
vncserver启动失败

### ISSUE THREAD

**Issue by CSYZQ** [22dm/linux_faq#49]
**个人信息**
- 学号：191250188
- 机器：172.29.4.85
- root 密码：123456

**描述你的问题**
安装tigervnc-server后输入vncserver命令，出现如下报错：remove this file if there is no X server host
![1](https://user-images.githubusercontent.com/55938455/88473688-9a3a4780-cf52-11ea-8c1d-05984d99ac71.png)

**你希望看到什么**
- vncserver启动成功

**Comment by CSYZQ** [comment]
删除 /tmp/.X11-unix/X1后应该好了

**Comment by CSYZQ** [comment]
但是用vncvierwer指令可以连接，但是用vnc viewer 软件连接172.29.4.85：1就报错timed out
![2](https://user-images.githubusercontent.com/55938455/88474386-5fd3a900-cf58-11ea-819d-d360ca4d3e23.png)
![1](https://user-images.githubusercontent.com/55938455/88474424-df617800-cf58-11ea-8bf7-2297738cb1d2.png)

**Comment by 22dm** [comment]
请检查你的防火墙是否开启了 5901 端口

**Comment by CSYZQ** [comment]
确实是防火墙的问题。。。但奇怪的是我确定之前已经添加了5901端口，但再上去看的时候就是没有。。

**Comment by 22dm** [comment]
防火墙配置默认只是当次有效，重启后会丢失，想要用久储存可以自行搜索相关教程
