### ISSUE TITLE
yum下载失败

### ISSUE THREAD

**Issue by Raquelnjq** [22dm/linux_faq#50]
**个人信息**
- 学号：191250107
- 机器：172.29.4.110
- root 密码：njq20010317
- vnc 密码：20010317

**描述你的问题**
yum install时失败

**你已经做了什么**
- 更换yum软件仓库
先试了下阿里的
![image](https://user-images.githubusercontent.com/68494887/88473897-6a8c3f00-cf54-11ea-80ee-00b353f7e4d2.png)
失败后编辑文件/etc/yum.repos.d/CentOS-Base.repo ，复制内容如下
![image](https://user-images.githubusercontent.com/68494887/88473929-b6d77f00-cf54-11ea-8cf5-2add50e8166d.png)
![image](https://user-images.githubusercontent.com/68494887/88473934-c48d0480-cf54-11ea-9e2b-5af06b751339.png)

**你希望看到什么**
- 能正常使用yum install

**屏幕截图**
最后出现如下情况
![image](https://user-images.githubusercontent.com/68494887/88473945-f30adf80-cf54-11ea-95c8-4e4395cac34e.png)
![image](https://user-images.githubusercontent.com/68494887/88473947-00c06500-cf55-11ea-9671-29d10c549960.png)
![image](https://user-images.githubusercontent.com/68494887/88473954-0fa71780-cf55-11ea-9381-b8250c89d258.png)

**附加信息**
- 也尝试过把所有/etc/yum.repos.d/CentOS-Base.repo文件中的$releasever换成7也无效

**Comment by 22dm** [comment]
https -> http

**Comment by Raquelnjq** [comment]
修改了，但是出现了这样.....
![image](https://user-images.githubusercontent.com/68494887/88474711-e3db6000-cf5b-11ea-8c06-77cf99123612.png)

**Comment by 22dm** [comment]
你有拨 p.nju 吗，校内访问外网需要认证，请参考《课程指南》中的相关章节

**Comment by Raquelnjq** [comment]
好了！万分感谢！
