### ISSUE TITLE
使用putty登录时提示network error ：connection refused

### ISSUE THREAD

**Issue by CSYZQ** [22dm/linux_faq#51]
**个人信息**
- 学号：191250188
- 机器：172.29.4.85
- root 密码：123456

**描述你的问题**
使用ssh登录时提示network error ：connection refused

**你已经做了什么**
- 完成openssh配置，关闭selinux

![1](https://user-images.githubusercontent.com/55938455/88474860-3d905a00-cf5d-11ea-9666-76bebf5a611d.png)
![2](https://user-images.githubusercontent.com/55938455/88474881-6c0e3500-cf5d-11ea-9890-995c21a38310.png)

**你希望看到什么**
- 可以使用ssh连接

**Comment by 22dm** [comment]
参考 #45

**Comment by CSYZQ** [comment]
去防火墙那看了，发现已经有2200端口
![1](https://user-images.githubusercontent.com/55938455/88475169-29019100-cf60-11ea-825c-3e145b484b70.png)

**Comment by CSYZQ** [comment]
![2](https://user-images.githubusercontent.com/55938455/88475243-a0372500-cf60-11ea-9862-c627b23b841e.png)
请问这是什么问题

**Comment by 22dm** [comment]
点“是”即可

**Comment by CSYZQ** [comment]
非常感谢
