### ISSUE TITLE
通过云平台重启云主机用时过长

### ISSUE THREAD

**Issue by linzs148** [22dm/linux_faq#54]
**个人信息**
- 学号：191250088
- 机器：172.29.4.172
- root 密码：
- vnc 密码：

**描述你的问题**
由于错误操作我把云主机重装了一遍，然后安装完centos出错，在云平台重启就一直卡在这

**屏幕截图**
![image](https://user-images.githubusercontent.com/56420840/88508702-0b8cff80-d012-11ea-8068-33f08847b7ca.png)

**Comment by 22dm** [comment]
请其他出现此问题的同学在下方留言学号
