### ISSUE TITLE
使用selinux开放端口后出现connection refused

### ISSUE THREAD

**Issue by NIL-zhuang** [22dm/linux_faq#57]
**个人信息**
- 学号：181830266
- 机器：172.29.4.69
- root 密码：centos
- vnc 密码：centos

**描述你的问题**
在运行`semanage port -a -t http_port_t -p tcp port_num`后，ssh登出再登录，出现connection refused，如果连接其他已开放端口例如2200，则出现connection timeout

**你已经做了什么**
- 更改sshd_config文件，添加port 2200
- 查看`semanage port -l | grep 22`可以看到开放了22和2200的tcp端口
- 关闭系统防火墙
- 已在机器上复现该问题

**Comment by 22dm** [comment]
没有发现问题，2200 可以正常连接，也许你已经修好了？
