### ISSUE TITLE
命令行连接校园网方式

### ISSUE THREAD

**Issue by NIL-zhuang** [22dm/linux_faq#6]
**个人信息**
- 学号：181830266
- 机器：172.29.4.69
- root 密码：not necessary
- vnc 密码：not necessary

**描述你的问题**

* 该通过什么命令登录/退出南大校园网p.nju.edu.cn

**你已经做了什么**

* 安装并配置好了服务器

**你希望看到什么**

* 可以在纯命令行环境下连接校园网并ping通www.baidu.com

**屏幕截图**

**附加信息**
- 我可以通过 ssh / VNC 连接到云主机

**Comment by 22dm** [comment]
请参见《课程指南》中 “Portal 认证上网” 一节
